# Generated by Django 4.2.6 on 2023-10-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0005_remove_order_product_list'),
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.productlist')),
            ],
        ),
    ]
