# Generated by Django 4.2.6 on 2023-10-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
        ('cart', '0003_remove_cart_products_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_list.productlist'),
            preserve_default=False,
        ),
    ]
