# Generated by Django 4.2.6 on 2023-10-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('date_of_receiving', models.DateField()),
                ('products', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
