# Generated by Django 4.2.6 on 2023-10-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
        ('order', '0003_rename_user_id_order_user_remove_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product_list.productlist'),
            preserve_default=False,
        ),
    ]
