# Generated by Django 4.2.6 on 2023-10-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_product_order_product_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_list',
        ),
    ]
